name: flutter_klarna_payment
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^12.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_klarna_payment.flutter_klarna_payment
        pluginClass: FlutterKlarnaPaymentPlugin
      ios:
        pluginClass: FlutterKlarnaPaymentPlugin
